
name: sample_flow
on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - name: Install npm & run app
      run: |
        export NODE_OPTIONS="--max_old_space_size=3072"
        npm install --legacy-peer-deps && npm ci --legacy-peer-deps && npm run
        ls -al
        mkdir out
        
    - name: remove node modules
      run: ls -al 
    - name: copy files
      run: |
        ls -al
        cd out/
        ls -al 
        mkdir rename_file
        ls -al
        for i in $(find . -name "*.html" -not -name "johnny.html" -not -name "index.html" -not -name "404.html" -not -name "sitemap.html"); do echo $i | sed 's|\(.*\)/.*|\1|' | xargs -I% mkdir -p rename_file% ;mv "$i" "rename_file${i%.html}";done      
    - name: sync s3
      run: |
        ls -al
        cd rename_file/
        ls -al
        pwd
       
